### ISSUE TITLE
baselines.ppol

### ISSUE THREAD

**Issue by GaoPeng97** [VincentYu68/SymmetryCurriculumLocomotion#1]
sorry to bother you, I meet a problem "No module named baselines.ppo1" what does this mean?

**Comment by GaoPeng97** [comment]
I followed the guide in your links, does it have any relation with python version?

**Comment by GaoPeng97** [comment]
I solved it, Maybe you have given wrong command " mpirun -np 8 python -m **baselines.**baselines.ppo1.run_walker3d_staged_learning",  one baselines is redundant, this command should be changed as" mpirun -np 8 python -m baselines.ppo1.run_walker3d_staged_learning"

**Comment by VincentYu68** [comment]
Thanks for catching that!  There is indeed an extra 'baselines' in the command. I was testing the command outside the whole folder, which led to this mistake.
